### PR TITLE
Update readme to include an example .sqlmigrate file

### PR DESCRIPTION
**Pull request by mkapnick**
References #1

### CODE REVIEW

**Comment by jeremija** [comment]
Thanks!

**Comment by jeremija** [comment]
@mkapnick what was exactly the point of this pull request? i made a mistake of accepting it too quickly because i was on my phone, and it was only a README update.

there was already a usage example in the README.md:

``` javascript
require('sqlmigrate').create({
  migrationsDir: 'db/migrations',
  dbConfig: {
    database: 'sqlmigrate_test',
    host: '127.0.0.1',
    port: 3306,
    user: 'travis',
    password: ''
  }
})
.migrate();
```

and what you added seems counter-intuitive for a number of reasons:
1. it just exports a configuration object
2. the method `start()` does not actually start the migration
3. it seems redundant compared to what was already there

**Comment by mkapnick** [comment]
That example was producing the following error for me:

```
/Users/mk/.nvm/versions/node/v6.2.2/lib/node_modules/sqlmigrate/lib.js:73
  options.dbConfig.multipleStatements = true;
TypeError: Cannot set property 'multipleStatements' of undefined
    at Object.create (/Users/mk/.nvm/versions/node/v6.2.2/lib/node_modules/sqlmigrate/lib.js:73:39)
    at start (/Users/mk/.nvm/versions/node/v6.2.2/lib/node_modules/sqlmigrate/bin/sqlmigrate:15:24)
    at Object.<anonymous> (/Users/mk/.nvm/versions/node/v6.2.2/lib/node_modules/sqlmigrate/bin/sqlmigrate:38:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

`create` gets called twice in that example, once from the `.sqlmigrate` file and then again here

```
  try {
    var config = require(path.join(process.cwd(), '.sqlmigrate'));
  } catch (err) {
    error('no `.sqlmigrate` file found in working directory');
    process.exit(1);
  }
  var sqlmigrate = lib.create(config);
```

I was able to get the cli command `sqlmigrate` to work by instead exporting the configuration options

**Comment by jeremija** [comment]
You're right. The example shows how to use this library pragmatically, rather than the bundled `sqlmigrate` script, which requires the `.sqlmigrate` file. I completely forgot that this script existed 😄 .

Still, I think there was no need to define a `start()` function as it could've been simpler:

``` javascript
module.exports = {
  migrationsDir: 'src/db/migrations',
    dbConfig: {
    database: 'dbName',
    host: '127.0.0.1',
    port: '3306',
    user: 'user',
    password: 'password'
  }
};
```

<strike>
or it could be a JSON:

``` json
{
  "migrationsDir": "src/db/migrations",
  "dbConfig": {
    "database": "dbName",
    "host": "127.0.0.1",
    "port": "3306",
    "user": "user",
    "password": "password"
  }
}
```

</strike>

I'll edit that. And I'll also add a more detailed description about how to use the `sqlmigrate` cli tool.

**Pull request merged**
